server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://192.168.2.11:3306/meeting
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
logging:
  level:
    root: warn