server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://192.168.2.220:3306/meeting2?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: warn