server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mwd?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: mwd
    password: mwd
  jpa:
    show-sql: true